name: Go

on:
  push:
    paths:
      - 'main.go'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Tidy dependencies
      run: go mod tidy

    - name: Build
      run: go build -v -o goober-central ./...

    - name: Test
      run: go test -v ./...

    - name: Create or Update Release
      id: create-release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: -${{ github.sha }}
        name: Release -${{ github.sha }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./goober-central
